// Positive = desirable, negative = expensive. Amateur rank: 0 (6) ... 1 (A).
export const BEGINNER_WEIGHTS = Object.freeze({
  PLAY: 20, RANK_COST: 1, TRUMP_COST: 24,
  THROW_IN: 6, PICKUP_THROW_IN: 5, PASS: 0, TAKE: -100,
});
export const AMATEUR_WEIGHTS = Object.freeze({
  ATTACK: 10, LOW_PLAIN_CARD: 8, SHED_HIGH_PLAIN_CARD: 4, SAME_RANK: 10,
  SMALL_TRUMP_COST: 12, HIGH_TRUMP_COST: 24, LAST_TRUMPS_COST: 14,
  TRUMPS_OUT_RESERVE: 6, FORCE_PICKUP: 22, KNOWN_COUNTER_COST: 12,
  OBSERVED_WEAKNESS: 3, REPEATED_OPENING_COST: 12,
  THROW_IN_COST: 6, PICKUP_THROW_IN: 9,
  DEFEND: 30, DEFENSE_RANK_COST: 8, FUTURE_DEFENSE_COST: 0.5,
  UNANSWERABLE_ATTACK_COST: 36, TAKE: -6, PICKUP_CARD_COST: 3,
  ENDGAME_TAKE_COST: 55, FINISH_HAND: 90, PENULTIMATE_CARD: 8, PASS: 0,
});
