import test from 'node:test';
import assert from 'node:assert/strict';
import {deck,beats} from '../src/game/cards.js';
import {createGame,act,legalActions,observation} from '../src/game/engine.js';
const c=id=>deck().find(c=>c.id===id);
function fixture(hands, stock=[]) {const s=createGame();Object.assign(s,{players:hands.map((h,id)=>({id,name:String(id),hand:h.map(c),out:false})),stock:stock.map(c),trump:'♠',trumpCard:c('♠6'),table:[],discarded:[],events:[],attacker:0,defender:1,actor:0,phase:'attack',taking:false,passed:[],limit:Math.min(6,hands[1].length)});return s;}
test('36 unique cards, six each, exposed trump drawn last',()=>{const s=createGame();assert.equal(new Set(deck().map(c=>c.id)).size,36);assert.deepEqual(s.players.map(p=>p.hand.length),[6,6,6]);assert.equal(s.stock.length,18);assert.equal(s.stock[0].id,s.trumpCard.id);});
test('same suit higher or trump, trump only by higher trump',()=>{assert.ok(beats(c('♥7'),c('♥6'),'♠'));assert.ok(beats(c('♠6'),c('♥A'),'♠'));assert.ok(!beats(c('♥A'),c('♠6'),'♠'));assert.ok(!beats(c('♠6'),c('♠7'),'♠'));assert.ok(!beats(c('♦A'),c('♥6'),'♠'));});
test('rank matching, defense ranks, hand limit and immutable state',()=>{let s=fixture([['♥6','♦7','♣9'],['♥7','♠8'],['♦6']]);const original=structuredClone(s);s=act(s,{type:'attack',card:'♥6'});assert.deepEqual(original.table,[]);s=act(s,{type:'defend',card:'♥7',target:0});assert.ok(legalActions(s).some(a=>a.card==='♦7'));assert.ok(!legalActions(s).some(a=>a.card==='♣9'));s=act(s,{type:'attack',card:'♦7'});s=act(s,{type:'take'});assert.deepEqual(legalActions(s),[{type:'pass'}]);});
test('pickup allows throwing in; defender skipped',()=>{let s=fixture([['♥6','♦6'],['♥7','♣8','♣9'],['♠9']]);s=act(s,{type:'attack',card:'♥6'});s=act(s,{type:'take'});s=act(s,{type:'attack',card:'♦6'});while(s.round===1&&!s.finished)s=act(s,{type:'pass'});assert.equal(s.attacker,2);assert.equal(s.players[1].hand.length,5);assert.equal(s.discarded.length,0);});
test('successful defense discards; defender attacks next',()=>{let s=fixture([['♥6','♣8'],['♥7','♣9'],['♠9']]);s=act(s,{type:'attack',card:'♥6'});s=act(s,{type:'defend',card:'♥7',target:0});s=act(s,{type:'pass'});s=act(s,{type:'pass'});assert.equal(s.attacker,1);assert.equal(s.discarded.length,2);});
test('refill original attacker first, defender last',()=>{let s=fixture([['♥6'],['♥7'],['♣9']],['♠6','♦6','♦7','♦8','♦9','♦10','♦J']);s=act(s,{type:'attack',card:'♥6'});s=act(s,{type:'defend',card:'♥7',target:0});s=act(s,{type:'pass'});assert.equal(s.players[0].hand.length,6);assert.equal(s.players[2].hand.length,2);assert.equal(s.players[1].hand.length,0);assert.ok(s.players[1].out);assert.equal(s.attacker,2);assert.ok(s.players[2].hand.some(c=>c.id==='♠6'));});
test('last player loses and all-out is draw',()=>{for(const last of [['♣9'],[]]){let s=fixture([['♥6'],['♥7'],last]);s=act(s,{type:'attack',card:'♥6'});s=act(s,{type:'defend',card:'♥7',target:0});if(!s.finished)s=act(s,{type:'pass'});assert.ok(s.finished);assert.equal(s.loser,last.length?2:null);}});
test('illegal action rejected; observation hides private information',()=>{const s=createGame();assert.throws(()=>act(s,{type:'take'}));const o=observation(s);assert.ok(!('stock' in o));assert.ok(o.players.every(p=>!('hand' in p)));o.hand.length=0;assert.equal(s.players[s.actor].hand.length,6);});
